version: '3.8'

services:
  # Single Redis instance
  redis-single:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass EUgWXeM2uWBEdcQEmto2iKuyN5IWnKsk
    profiles:
      - single

  # Redis Cluster nodes
  redis-cluster-1:
    image: redis:7-alpine
    ports:
      - "7000:7000"
    command: redis-server --port 7000 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-cluster-1-data:/data
    profiles:
      - cluster

  redis-cluster-2:
    image: redis:7-alpine
    ports:
      - "7001:7001"
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-cluster-2-data:/data
    profiles:
      - cluster

  redis-cluster-3:
    image: redis:7-alpine
    ports:
      - "7002:7002"
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-cluster-3-data:/data
    profiles:
      - cluster

  redis-cluster-4:
    image: redis:7-alpine
    ports:
      - "7003:7003"
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-cluster-4-data:/data
    profiles:
      - cluster

  redis-cluster-5:
    image: redis:7-alpine
    ports:
      - "7004:7004"
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-cluster-5-data:/data
    profiles:
      - cluster

  redis-cluster-6:
    image: redis:7-alpine
    ports:
      - "7005:7005"
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-cluster-6-data:/data
    profiles:
      - cluster

  # Cluster initialization service
  redis-cluster-init:
    image: redis:7-alpine
    depends_on:
      - redis-cluster-1
      - redis-cluster-2
      - redis-cluster-3
      - redis-cluster-4
      - redis-cluster-5
      - redis-cluster-6
    command: |
      sh -c "
        sleep 10
        redis-cli --cluster create redis-cluster-1:7000 redis-cluster-2:7001 redis-cluster-3:7002 redis-cluster-4:7003 redis-cluster-5:7004 redis-cluster-6:7005 --cluster-replicas 1 --cluster-yes
      "
    profiles:
      - cluster

volumes:
  redis-cluster-1-data:
  redis-cluster-2-data:
  redis-cluster-3-data:
  redis-cluster-4-data:
  redis-cluster-5-data:
  redis-cluster-6-data:
