# HikariCP 최적화 설정
spring:
  datasource:
    hikari:
      maximum-pool-size: 50        # 증가 (기본: 10)
      minimum-idle: 20             # 증가 (기본: 10)
      connection-timeout: 3000     # 3초
      idle-timeout: 300000         # 5분
      max-lifetime: 900000         # 15분
      leak-detection-threshold: 60000  # 연결 누수 감지

  # OSIV 비활성화 - 프로덕션 최적화
  jpa:
    open-in-view: false
    properties:
      hibernate:
        # 배치 처리 최적화
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        # 쿼리 계획 캐시 최적화
        query:
          plan_cache_max_size: 2048
